server:
  port: 8002

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 1MB
  devtools:
    restarter:
      enabled: true
hcloud:
  port: 7777
aliyun:
  service:
    REGION: cn-hangzhou
    ROLE: acs:ram::1727804214750599:role/AliyunFCLogExecutionRole
  user:
    accessKey: LTAI4GH6AT8SMifeXJk2dQch
    accessSecretKey: EPZ6KLb6NMV25fEuGjNnJuFrrfJeNE
    accountId: 1727804214750599