mode: hcloud
# hcloud means just use HCloudProvider
# alicloud means just use AliCloudProvider
# mixed means both HCloudProvider and AliCloudProvider are used
server:
  port: 30342
  address: 0.0.0.0
  exportAddress: 10.0.89.1
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
  devtools:
    restarter:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/jccplatform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
  data:
    mongodb:
      username: admin
      password: secret
      host: localhost
      port: 30343
      database: jccplatform
hcloud:
  port: 30347
  batchScale: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  table:
    auto: create

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.fc.springcloud.mapping: debug
File:
  base-dir: ./
mesh:
  use: true
  internalGatewayLocation: 10.0.89.3:2046
  externalGatewayLocation: 127.0.0.1:30344
  routerPrefix: /function/
  definition: 10.0.0.42:50051,10.0.0.7:50051,10.0.0.19:50051
  target: 10.0.0.42:40041
  prom:
    target: 127.0.0.1:30349
  trace:
    host: 0.0.0.0
    port: 6832
  runtime:
    java: registry.cn-shanghai.aliyuncs.com/jointfaas-serverless/env-java:v1.0
    python: registry.cn-shanghai.aliyuncs.com/jointfaas-serverless/env-python:v3.0
    nodejs: registry.cn-shanghai.aliyuncs.com/jointfaas-serverless/env-javascript:v7.2
aliyun:
  service:
    REGION: cn-hangzhou
    ROLE: acs:ram::***:role/fnf-execution-default-role
  user:
    accessKey:
    accessSecretKey:
    accountId: