spring:
  profiles:
#    active: dev
    active: test
aliyun:
  service:
    REGION: cn-hangzhou
    ROLE: acs:ram::1727804214750599:role/AliyunFCLogExecutionRole
  user:
    accessKey: LTAI4GH6AT8SMifeXJk2dQch
    accessSecretKey: EPZ6KLb6NMV25fEuGjNnJuFrrfJeNE
    accountId: 1727804214750599