server:
  port: 8002
  address: 127.0.0.1
spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
  devtools:
    restarter:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jccplatform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    mongodb:
      username: jcc
      password: 123456
      host: 127.0.0.1
      port: 27017
      database: jccplatform
hcloud:
  port: 7777

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config: classpath:logback-jcc.xml
  file:
    path: logs/${project.name}-${project.version}
File:
  base-dir: ./
aliyun:
  service:
    REGION: cn-hangzhou
    ROLE: acs:ram::1727804214750599:role/AliyunFCLogExecutionRole
  user:
    accessKey: LTAI4GH6AT8SMifeXJk2dQch
    accessSecretKey: EPZ6KLb6NMV25fEuGjNnJuFrrfJeNE
    accountId: 1727804214750599