server:
  port: 8002
  address: 127.0.0.1
  exportAddress: 127.0.0.1
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
  devtools:
    restarter:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jccplatform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    mongodb:
      username: jcc
      password: 123456
      host: 127.0.0.1
      port: 27017
      database: jccplatform
hcloud:
  port: 7777

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.fc.springcloud.mapping: debug
File:
  base-dir: ./